package com.example.kat.pollinghelper.processor.opera;

/**
 * Created by KAT on 2016/6/8.
 */
public enum ArgumentTag {
    AT_PROJECT_RECORD_CURRENT,
    AT_MISSION_RECORD_CURRENT,
    AT_SENSOR_ENTITY_CURRENT,
    AT_LIST_SENSOR_CONFIG,
    AT_LIST_PROJECT_CONFIG,
    AT_LIST_PROJECT_ENTITY,
    AT_LIST_ENTITY_DESERTED,
    AT_LIST_SENSOR_ENTITY_EXIST,
    AT_LIST_SENSOR_ENTITY_DESERTED,
    AT_LIST_LATEST_PROJECT_RECORD,
    AT_SCOUT_CELL_CURRENT_CLICKED,
    AT_SCOUT_ENTITY_FEEDBACK,
    AT_RUNNABLE_SUCCESS,
    AT_RUNNABLE_FAILED,
    AT_QUERY_INFO,
    AT_DATA_LISTENER
    ;

    public static String PROJECT_CONFIG_CHANGED = "PROJECT_CONFIG_CHANGED";
    public static String SENSOR_CONFIG_CHANGED = "SENSOR_CONFIG_CHANGED";
    public static String RESTORE_PROJECT_AND_SENSOR_CONFIG = "RESTORE_PROJECT_AND_SENSOR_CONFIG";
}
