package com.example.kat.pollinghelper.processor.opera;

/**
 * Created by KAT on 2016/6/8.
 */
public enum ArgumentTag {
    AT_HANDLER_UI_FEEDBACK,
    AT_PROJECT_RECORD_CURRENT,
    AT_MISSION_RECORD_CURRENT,
    AT_SENSOR_ENTITY_CURRENT,
    AT_LIST_SENSOR_CONFIG,
    AT_LIST_PROJECT_CONFIG,
    AT_LIST_PROJECT_ENTITY,
    AT_LIST_ENTITY_DESERTED,
    AT_LIST_SENSOR_ENTITY_EXIST,
    AT_LIST_SENSOR_ENTITY_DESERTED,
    AT_LIST_LATEST_PROJECT_RECORD,
    AT_CONFIG_LIST_ITEM_CURRENT_CLICKED,
    AT_CONFIG_LIST_ITEM_ENTITY_NEW,
    AT_RUNNABLE_IMPORT_PROJECT_AND_SENSOR_CONFIGS,
    AT_RUNNABLE_FINISH_PROCESSOR,
    AT_RUNNABLE_UPDATE_SENSOR_DATA,
    AT_RUNNABLE_EXPORT_POLLING_CONFIGS_SUCCESS,
    AT_RUNNABLE_EXPORT_POLLING_CONFIGS_FAILED,
    AT_RUNNABLE_EXPORT_SENSOR_CONFIGS_SUCCESS,
    AT_RUNNABLE_EXPORT_SENSOR_CONFIGS_FAILED,
    ;

    public static String PROJECT_CONFIG_CHANGED = "PROJECT_CONFIG_CHANGED";
    public static String SENSOR_CONFIG_CHANGED = "SENSOR_CONFIG_CHANGED";
    public static String RESTORE_PROJECT_AND_SENSOR_CONFIG = "RESTORE_PROJECT_AND_SENSOR_CONFIG";
}
