package com.example.kat.pollinghelper.processor.opera;

/**
 * Created by KAT on 2016/5/5.
 */
public enum OperaType {
    OT_IMPORT_PROJECT_AND_SENSOR_CONFIGS,
    OT_EXPORT_POLLING_PROJECT_RECORD,
    OT_UPDATE_SINGLE_MISSION_SENSOR_VALUE,
    OT_EXPORT_POLLING_MISSION_RECORD,
    OT_EXPORT_POLLING_CONFIGS,
    OT_IMPORT_SENSOR_CONFIG,
    OT_EXPORT_SENSOR_CONFIG,
    OT_CREATE_POLLING_DATABASE,
    OT_SCAN_BLE_SENSOR,
    OT_QUERY_RECORD,
    OT_REQUEST_SENSOR_COLLECTION,
    OT_MODIFY_BASE_STATION_IP,
    OT_MODIFY_BASE_STATION_PORT,
    OT_MODIFY_DATA_REQUEST_CYCLE,
    OT_MODIFY_SCAN_BLE_CYCLE,
    OT_MODIFY_SCAN_BLE_DURATION,
    OT_INSTALL_WARN_LISTENER,
    OT_UPDATE_SENSOR_MEASURE_NAME,
    OT_UPDATE_MULTIPLE_MISSION_SENSOR_VALUE,
    OT_JUDGE_ARRESTER_GROUP
}
